version: '3.8'

services:
  # Express TypeScript application
  app:
    build:
      context: .
      target: ${NODE_ENV:-production}
    container_name: chesscraftserver
    restart: unless-stopped
    ports:
      - "${PORT:-3333}:3333"
    volumes:
      - ./uploads:/app/uploads
      # For development: mount source code to enable hot reloading
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3333}
      - MONGO_URI=${MONGO_URI}
    networks:
      - chesscraft-network

  # Development service for hot reloading (only in dev mode)
  dev:
    build:
      context: .
      target: deps
    container_name: chesscraftserver-dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3333}
      - MONGO_URI=${MONGO_URI}
    networks:
      - chesscraft-network
    profiles: ["dev"]

networks:
  chesscraft-network:
    driver: bridge